### ISSUE TITLE
SIGSEGV on all inputs

### ISSUE THREAD

**Issue by seanmorris** [CircleCI-Public/circleci-cli#1059]
## Meta:

**CircleCI CLI Version:**
```
$ circleci version
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x609084]

goroutine 1 [running]:
net/url.(*URL).ResolveReference(0x0, 0xc00031f850)
        /usr/local/go/src/net/url/url.go:1082 +0x84
github.com/CircleCI-Public/circleci-cli/api/rest.NewFromConfig({0xc000164030, 0x2a}, 0xc00031fbb0)
        /home/circleci/project/api/rest/client.go:54 +0x1bf
github.com/CircleCI-Public/circleci-cli/api/collaborators.NewCollaboratorsRestClient(...)
        /home/circleci/project/api/collaborators/collaborators_rest.go:23
github.com/CircleCI-Public/circleci-cli/cmd.newOrbCommand(0xc000136360)
        /home/circleci/project/cmd/orb.go:107 +0x73
github.com/CircleCI-Public/circleci-cli/cmd.MakeCommands()
        /home/circleci/project/cmd/root.go:162 +0x5c5
github.com/CircleCI-Public/circleci-cli/cmd.CommandStr()
        /home/circleci/project/cmd/root.go:66 +0x17
github.com/CircleCI-Public/circleci-cli/cmd.Execute()
        /home/circleci/project/cmd/root.go:47 +0x29
main.main()
        /home/circleci/project/main.go:11 +0x13

```

**Operating System:**
```
Linux 6.1.0-21-amd64 Debian 6.1.90-1 (2024-05-03) x86_64 GNU/Linux
```

**CircleCI CLI Diagnostic:**

```
$ circleci diagnostic
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x609084]

goroutine 1 [running]:
net/url.(*URL).ResolveReference(0x0, 0xc00031f850)
        /usr/local/go/src/net/url/url.go:1082 +0x84
github.com/CircleCI-Public/circleci-cli/api/rest.NewFromConfig({0xc000164030, 0x2a}, 0xc00031fbb0)
        /home/circleci/project/api/rest/client.go:54 +0x1bf
github.com/CircleCI-Public/circleci-cli/api/collaborators.NewCollaboratorsRestClient(...)
        /home/circleci/project/api/collaborators/collaborators_rest.go:23
github.com/CircleCI-Public/circleci-cli/cmd.newOrbCommand(0xc000136360)
        /home/circleci/project/cmd/orb.go:107 +0x73
github.com/CircleCI-Public/circleci-cli/cmd.MakeCommands()
        /home/circleci/project/cmd/root.go:162 +0x5c5
github.com/CircleCI-Public/circleci-cli/cmd.CommandStr()
        /home/circleci/project/cmd/root.go:66 +0x17
github.com/CircleCI-Public/circleci-cli/cmd.Execute()
        /home/circleci/project/cmd/root.go:47 +0x29
main.main()
        /home/circleci/project/main.go:11 +0x13
```

---

## Current behavior:
`SIGSEGV`

## Expected behavior:
It should run.

## When did this begin / Was this previously working?:
Problem started immediately after running `curl -fLSs https://raw.githubusercontent.com/CircleCI-Public/circleci-cli/main/install.sh | sudo bash`

**Comment by cci-jassad** [comment]
Thanks for the report @seanmorris !   We're looking into it.

**Comment by abdelDriowya** [comment]
I setup a Debian Bookworm machine, I was unable to reproduce using the same command you shared.
do you still have the issue
<img width="813" alt="Screenshot 2024-06-25 at 14 56 27" src="https://github.com/CircleCI-Public/circleci-cli/assets/111757332/b3236252-7625-4a4f-8a2e-84a82a1be62f">

**Comment by abdelDriowya** [comment]
can you try running circleci command with and without --host parameter.
for example : 
`circleci orb info circleci/shellcheck@1.2.0`
`circleci orb info circleci/shellcheck@1.2.0 --host https://circleci.com`
it maybe the configured host in your machine that is not setup correctly

**Comment by ohjinsoo** [comment]
Never mind, the real fix was to fix my CLI config at `~/.circleci/cli.yml`. The `host` field was corrupted with bad data. Fixing that fixed the CLI even with the environment variable not set.
