### ISSUE TITLE
Respect .gitignore or .dockerignore

### ISSUE THREAD

**Issue by jesstelford** [CircleCI-Public/circleci-cli#151]
Following on from [this thread](https://discuss.circleci.com/t/running-circleci-locally-should-allow-to-ignore-some-files/17447).

When running locally (eg `circleci local execute --job tests`), _all_ files in the current working directory are copied over to the docker container, causing errors that don't occur when run on circleci.com.

## Example

_(note: a reproducible case is available at https://github.com/jesstelford/local-circleci-test/pull/1)_

My project is written in nodejs, and has a dependency on the [`bcrypt`](https://www.npmjs.com/package/bcrypt) package:

`package.json`
```json
{
  "name": "test-project",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "dependencies": {
    "bcrypt": "^3.0.1"
  }
}
```

The `bcrypt` package gets installed into `node_modules/bcrypt`, so we add it to our `.gitignore`:

```
node_modules
```

Then we setup a job to run on circleci:

`.circleci/config.yml`
```
version: 2

jobs:
  tests:
    docker:
      # specify the version you desire here
      - image: circleci/node:carbon-browsers
    working_directory: /home/circleci/repo
    steps:
      - checkout
      - run: yarn
      - run: node -p "require('bcrypt').hashSync('password', 5)"
```

Then when we commit these 3 files, and run it on CircleCI.com, everything runs fine.

But if we try to run the following commands on an OSX machine, there are errors:

```bash
# creates the `node_modules` directory which is incorrectly copied to the docker image
yarn

# run the local circleci command
circleci local execute --job build
```

<details>
 <summary>Gives the following output</summary>

```
❯ circleci local execute --job build
Docker image digest: sha256:3d88cfffd448da07ff8ced22ccdca5adc09ff18e87dc7db9b8af5b8a47647c08
====>> Spin up Environment
Build-agent version 0.1.750-336e0196 (2018-09-13T19:48:06+0000)
Starting container circleci/node:carbon-browsers
  using image circleci/node@sha256:e116faa71d34d76287d6b2a81abeeadd5897f508e14b41391b29ed882c820022
Using build environment variables:
  BASH_ENV=/tmp/.bash_env-localbuild-1538887853
  CI=true
  CIRCLECI=true
  CIRCLE_BRANCH=the-error
  CIRCLE_BUILD_NUM=
  CIRCLE_JOB=build
  CIRCLE_NODE_INDEX=0
  CIRCLE_NODE_TOTAL=1
  CIRCLE_REPOSITORY_URL=git@github.com:jesstelford/local-circleci-test.git
  CIRCLE_SHA1=bbde846be5368499be3eb79f3154d4c017ab9122
  CIRCLE_SHELL_ENV=/tmp/.bash_env-localbuild-1538887853
  CIRCLE_WORKING_DIRECTORY=/home/circleci/repo
====>> Checkout code
  #!/bin/bash -eo pipefail
mkdir -p /home/circleci/repo && cp -r /tmp/_circleci_local_build_repo/. /home/circleci/repo
====>> yarn
  #!/bin/bash -eo pipefail
yarn
yarn install v1.9.4
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
Done in 2.34s.
====>> node -p "require('bcrypt').hashSync('password', 5)"
  #!/bin/bash -eo pipefail
node -p "require('bcrypt').hashSync('password', 5)"
module.js:682
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: /home/circleci/repo/node_modules/bcrypt/lib/binding/bcrypt_lib.node: invalid ELF header
    at Object.Module._extensions..node (module.js:682:18)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/circleci/repo/node_modules/bcrypt/bcrypt.js:6:16)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
Error: Exited with code 1
Step failed
Error: runner failed
Task failed
```
</details>

---

However, if you remove `node_modules`, everything runs fine:

```bash
# clean up files that aren't meant to be copied to the docker image
rm -rf node_modules

# run the local circleci command
circleci local execute --job build
```

<details>
 <summary>Gives the following output</summary>

```
❯ circleci local execute --job build
Docker image digest: sha256:3d88cfffd448da07ff8ced22ccdca5adc09ff18e87dc7db9b8af5b8a47647c08
====>> Spin up Environment
Build-agent version 0.1.750-336e0196 (2018-09-13T19:48:06+0000)
Starting container circleci/node:carbon-browsers
  using image circleci/node@sha256:e116faa71d34d76287d6b2a81abeeadd5897f508e14b41391b29ed882c820022
Using build environment variables:
  BASH_ENV=/tmp/.bash_env-localbuild-1538887959
  CI=true
  CIRCLECI=true
  CIRCLE_BRANCH=the-error
  CIRCLE_BUILD_NUM=
  CIRCLE_JOB=build
  CIRCLE_NODE_INDEX=0
  CIRCLE_NODE_TOTAL=1
  CIRCLE_REPOSITORY_URL=git@github.com:jesstelford/local-circleci-test.git
  CIRCLE_SHA1=bbde846be5368499be3eb79f3154d4c017ab9122
  CIRCLE_SHELL_ENV=/tmp/.bash_env-localbuild-1538887959
  CIRCLE_WORKING_DIRECTORY=/home/circleci/repo
====>> Checkout code
  #!/bin/bash -eo pipefail
mkdir -p /home/circleci/repo && cp -r /tmp/_circleci_local_build_repo/. /home/circleci/repo
====>> yarn
  #!/bin/bash -eo pipefail
yarn
yarn install v1.9.4
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
Done in 5.15s.
====>> node -p "require('bcrypt').hashSync('password', 5)"
  #!/bin/bash -eo pipefail
node -p "require('bcrypt').hashSync('password', 5)"
$2b$05$XhiGPRaOV607/aGp9Th08OdyJPKFVQztuqWREyjTk4IYTPX1W5XXu
Success!
```
</details>

---

This is because:
- I am running on OSX
- the `bcrypt` package installs OS-specific binaries into `node_modules`
- `circleci-cli` then copies over `node_modules` to the docker image (ignoring my `.gitignore`)
- resulting in the `invalid ELF header` error.

**Comment by dnephin** [comment]
I think `local execute` should create a tarball from the list of files known to git, instead of copying everything or reading ignore files. This might look something like:

```
git ls-files | xargs tar -c | tar -x -C $TARGET
```

**Comment by jesstelford** [comment]
I like this ☝️

**Comment by eddiewebb** [comment]
@dnephin - looks like the local build command is just using a volume mount today (https://github.com/CircleCI-Public/circleci-cli/blob/master/cmd/build.go#L256) are you suggesting we mount an alternate/temp location with the filtered files?  

Also curious how this would play with the --no-checkout option, maybe its inconsequential...

**Comment by dnephin** [comment]
That volume is necessary to expose files to the container, but `circleci-agent` does not use that directory for running the job. In `circleci-agent` the `checkout` step is implemented as a copy from that bind mount directory to a `/tmp/something` directory. We've seen a bunch of errors with this copy operation, possibly because of file permissions, but it's not always clear.

The change I'm proposing is to replace the copy with the `git ls-files` version so the job runs with the same files as it would in cloud.

`--skip-checkout` is a bit misleading. It defaults to true, so the copy behaviour described above is the result of the `--skip-checkout` flag being enabled. Using `local execute --skip-checkout=false` will give you the same `checkout` behaviour as cloud, where it runs a `git clone`, etc.

**Comment by pikeas** [comment]
Strong agree, I'm hitting a related issue with the same root cause (not respecting gitignore / dockerignore).

If you have a large sub-directory in a project, for example `node_modules` (JS) or `.venv` (Python), a locally run checkout step takes an extremely long time, because of:

```
====>> Checkout code
  #!/bin/bash -eo pipefail
mkdir -p /root/project && cp -r /tmp/_circleci_local_build_repo/. /root/project
```

This cp command will very often copy hundreds of megabytes of data that is not needed by the build, causing the checkout step to take multiple minutes to complete. And, as @jesstelford mentioned, this results in an unexpected state during a build, which assumes that node_modules/.venv/etc are *not* present.

Please re-classify this as a bug rather than as an enhancement!

**Comment by ac21** [comment]
running into the same issue... great to git an update on this

**Comment by rasmuslp** [comment]
I have a `.env` file in the root of most of my projects. This often contains connection strings / authentication to databases and services. No wonder my applications can't connect to the database servers as specified in `.circleci/config.yml`.

Furthermore, copying `node_modules` makes the builds take forever. Since dependencies are installed as a step `.circleci/config.yml`, there is no point in them also being copied into the local build, just to get overwritten.

Support for _any_ kind of ignore file would be _greatly_ appreciated.

**Comment by eddiewebb** [comment]
Sharing an update because I greatly appreciated the pun from @ac21 

The work to make this happen is actually in another component that the CLI delegates building to.  I've mostly got the plumbing all coded up and passing, but need to cleanup a bit and get it scheduled with the next infra release. 

I'll share updates as I  make progress on that.

**Comment by eddiewebb** [comment]
🎉   
The latest build-agent has shipped, respecting .gitignore.  

To take advantage you will need to run `circleci update build-agent`

Thank you all for your feedback!
