### ISSUE TITLE
circleci update install is panicing for latest

### ISSUE THREAD

**Issue by varun06** [CircleCI-Public/circleci-cli#225]
```
circleci version
0.1.3341+6be51e4
```

```
circleci update check
A new release is available (0.1.4427)
You are running 0.1.3341
You can update with `circleci update install`
```

```
circleci update install
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x127d962]

goroutine 1 [running]:
github.com/CircleCI-Public/circleci-cli/logger.(*Logger).Debug(0x0, 0x1539208, 0x12, 0xc420143b60, 0x1, 0x1)
        /go/src/github.com/CircleCI-Public/circleci-cli/logger/logger.go:37 +0x22
github.com/CircleCI-Public/circleci-cli/cmd.update(0xc420155340, 0x0, 0x18450f0, 0x0, 0x0, 0xc420143c00, 0x12e4654, 0xc420133100)
        /go/src/github.com/CircleCI-Public/circleci-cli/cmd/update.go:149 +0x228
github.com/CircleCI-Public/circleci-cli/cmd.installUpdate(0xc420155340, 0x0, 0x18450f0, 0x0, 0x0, 0x0, 0x0)
        /go/src/github.com/CircleCI-Public/circleci-cli/cmd/update.go:124 +0x4d
github.com/CircleCI-Public/circleci-cli/cmd.newUpdateCommand.func4(0xc42017ec80, 0x18450f0, 0x0, 0x0, 0x0, 0x0)
        /go/src/github.com/CircleCI-Public/circleci-cli/cmd/update.go:55 +0x49
github.com/CircleCI-Public/circleci-cli/vendor/github.com/spf13/cobra.(*Command).execute(0xc42017ec80, 0x18450f0, 0x0, 0x0, 0xc42017ec80, 0x18450f0)
        /go/src/github.com/CircleCI-Public/circleci-cli/vendor/github.com/spf13/cobra/command.go:762 +0x468
github.com/CircleCI-Public/circleci-cli/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc420160500, 0xc420160780, 0xc420155360, 0xc420155350)
        /go/src/github.com/CircleCI-Public/circleci-cli/vendor/github.com/spf13/cobra/command.go:852 +0x30a
github.com/CircleCI-Public/circleci-cli/vendor/github.com/spf13/cobra.(*Command).Execute(0xc420160500, 0x0, 0xc420093740)
        /go/src/github.com/CircleCI-Public/circleci-cli/vendor/github.com/spf13/cobra/command.go:800 +0x2b
github.com/CircleCI-Public/circleci-cli/cmd.Execute()
        /go/src/github.com/CircleCI-Public/circleci-cli/cmd/root.go:26 +0x27
main.main()
        /go/src/github.com/CircleCI-Public/circleci-cli/main.go:9 +0x20

```

**Comment by yundt** [comment]
Thank you for reaching out! We had a bug in our update code around the version you have currently installed - it was fixed here: https://github.com/CircleCI-Public/circleci-cli/pull/168.

Unfortunately you need to delete your current version and re-install from scratch - sorry about that!
