### ISSUE TITLE
`circleci local execute` crashes with SIGSEGV

### ISSUE THREAD

**Issue by galen-wave** [CircleCI-Public/circleci-cli#361]
- [x] I have read [Contribution Guidelines](https://github.com/CircleCI-Public/circleci-cli/blob/master/CONTRIBUTING.md).
- [x] I have checked for similar issues and haven't found anything relevant.
- [x] This is not a security issue (which should be reported here: https://circleci.com/security/)

**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
Running a simple job with `circleci local execute` crashes with SIGSEGV.

**Can you provide an example?**

Minimal `.circleci/config.yml`:
```yaml
version: 2
jobs:
  venv:
    docker:
      - image: circleci/python:3.6.6
    steps:
      - run:
          command: |
            echo "hi"
workflows:
  version: 2
  build_and_test:
    jobs:
      - venv
```

command and output:
```
> circleci local execute -c .circleci/config.yml --job venv
Docker image digest: sha256:bd9e81940b9fb3c8f6fbf2d6e2af84ae3f669afe1fec4303653255f23f364aee
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x5e7077]

goroutine 28 [running]:
encoding/json.(*Encoder).Encode(0x0, 0xfb1380, 0xc000112070, 0xc000112070, 0x0)
	/usr/local/go/src/encoding/json/stream.go:198 +0x37
github.com/circleci/build-agent/pkg/eventprocessor.(*stubServer).ProcessTaskEvent(0xc00040c000, 0x11d0c40, 0xc00014e2a0, 0xc000112070, 0x0, 0x0, 0x0)
	/home/circleci/project/pkg/eventprocessor/server.go:45 +0xcf
github.com/circleci/build-agent/common/protocol._EventProcessor_ProcessTaskEvent_Handler(0xf53c00, 0xc00040c000, 0x11d0c40, 0xc00014e2a0, 0xc0002580c0, 0x0, 0x11d0c40, 0xc00014e2a0, 0xc000034050, 0x4f)
	/home/circleci/project/common/protocol/protocol.pb.go:1705 +0x217
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00042c000, 0x11db260, 0xc000306900, 0xc00011a000, 0xc0004002d0, 0x18ad3a0, 0x0, 0x0, 0x0)
	/go/pkg/mod/google.golang.org/grpc@v1.24.0/server.go:995 +0x460
google.golang.org/grpc.(*Server).handleStream(0xc00042c000, 0x11db260, 0xc000306900, 0xc00011a000, 0x0)
	/go/pkg/mod/google.golang.org/grpc@v1.24.0/server.go:1275 +0xd97
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc00040e0d0, 0xc00042c000, 0x11db260, 0xc000306900, 0xc00011a000)
	/go/pkg/mod/google.golang.org/grpc@v1.24.0/server.go:710 +0xbb
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/go/pkg/mod/google.golang.org/grpc@v1.24.0/server.go:708 +0xa1
```

**What is the expected behavior?**
It should run the job.
**Which version of the CLI and OS are you using? Did this work in previous versions?**
Mac OS X 10.15.3
Docker Desktop 2.2.0.0 (42247)
circleci 0.1.5879+416032d (via Homebrew)

I haven't restarted since installing Docker, but docker commands run fine from the command line.

Please provide the output of `circleci version` and `circleci diagnostic`.
```
> circleci version
0.1.5879+416032d
```
I first ran without having run `circleci setup`:
```
> circleci diagnostic

---
CircleCI CLI Diagnostics
---
Debugger mode: false
Config found: /Users/galen/.circleci/cli.yml
API host: https://circleci.com
API endpoint: graphql-unstable
Error: please set a token with 'circleci setup'
You can create a new personal API token here:
https://circleci.com/account/api
```
after setting up a token (I still get the same failure):
```
Debugger mode: false
Config found: /Users/galen/.circleci/cli.yml
API host: https://circleci.com
API endpoint: graphql-unstable
OK, got a token.
Trying an introspection query on API...
Ok.
Hello, Galen O'Sullivan.
```

**If you have any questions, feel free to ping us at @CircleCI-Public/x-team.**

**Comment by sebglon** [comment]
Hi, I have the same error with the repo: https://github.com/CircleCI-Public/circleci-demo-go.git

```
$ circleci version
0.1.5879+416032d
```

```
$ circleci diagnostic

---
CircleCI CLI Diagnostics
---
Debugger mode: false
Config found: /home/sebastien/.circleci/cli.yml
API host: https://circleci.com
API endpoint: graphql-unstable
OK, got a token.
Trying an introspection query on API... 
Ok.
Hello, Sébastien GLON.
```

**Comment by sebglon** [comment]
Hi,
I have the same error with the fresh build of the master branch.

```
circleci-cli local execute -c process.yml 
Docker image digest: sha256:bd9e81940b9fb3c8f6fbf2d6e2af84ae3f669afe1fec4303653255f23f364aee
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x5e7077]

goroutine 118 [running]:
encoding/json.(*Encoder).Encode(0x0, 0xfb1380, 0xc00021c7e0, 0xc00021c7e0, 0x0)
	/usr/local/go/src/encoding/json/stream.go:198 +0x37
github.com/circleci/build-agent/pkg/eventprocessor.(*stubServer).ProcessTaskEvent(0xc000208600, 0x11d0c40, 0xc0004cdf80, 0xc00021c7e0, 0x0, 0x0, 0x0)
	/home/circleci/project/pkg/eventprocessor/server.go:45 +0xcf
github.com/circleci/build-agent/common/protocol._EventProcessor_ProcessTaskEvent_Handler(0xf53c00, 0xc000208600, 0x11d0c40, 0xc0004cdf80, 0xc00049b440, 0x0, 0x11d0c40, 0xc0004cdf80, 0xc000454cc0, 0x51)
	/home/circleci/project/common/protocol/protocol.pb.go:1705 +0x217
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0000d1a20, 0x11db260, 0xc000488300, 0xc0000c8700, 0xc0003f68d0, 0x18ad3a0, 0x0, 0x0, 0x0)
	/go/pkg/mod/google.golang.org/grpc@v1.24.0/server.go:995 +0x460
google.golang.org/grpc.(*Server).handleStream(0xc0000d1a20, 0x11db260, 0xc000488300, 0xc0000c8700, 0x0)
	/go/pkg/mod/google.golang.org/grpc@v1.24.0/server.go:1275 +0xd97
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc0004bc020, 0xc0000d1a20, 0x11db260, 0xc000488300, 0xc0000c8700)
	/go/pkg/mod/google.golang.org/grpc@v1.24.0/server.go:710 +0xbb
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/go/pkg/mod/google.golang.org/grpc@v1.24.0/server.go:708 +0xa1

$ circleci-cli version
0.0.0-dev+dirty-local-tree

```

**Comment by dnephin** [comment]
Thank you for the bug report! I believe this was a bug introduced in a recent change. 

I've just pushed a fix. If you run `circleci update build-agent` you should get the new image and the panic should be fixed.

**Comment by sebglon** [comment]
Thanks work well for me.

**Comment by javiercornejo** [comment]
Works for me too... but until now your have the cli with the bug in the installation link ;)

**Comment by marcomorain** [comment]
This has been fixed, please re-open the issue if you have any further issues.
