### ISSUE TITLE
Checking for updates... panic: semver: Parse(0.1.15410_1): Invalid character(s) found in patch number "15410_1"

### ISSUE THREAD

**Issue by alexjurkiewicz** [CircleCI-Public/circleci-cli#610]
**CircleCI CLI Version:**
`0.1.15384+149d854 (homebrew)`

Autoupdate check fails:

```bash
❯ circleci config validate
⠇ Checking for updates... panic: semver: Parse(0.1.15410_1): Invalid character(s) found in patch number "15410_1"

goroutine 1 [running]:
github.com/blang/semver.MustParse(0xc000408b10, 0xb, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	github.com/blang/semver@v3.5.1+incompatible/semver.go:319 +0x245
github.com/CircleCI-Public/circleci-cli/update.checkFromHomebrew(0xc000306ab0, 0xc000306ab0, 0x0)
	github.com/CircleCI-Public/circleci-cli/update/update.go:93 +0x265
github.com/CircleCI-Public/circleci-cli/update.CheckForUpdates(0x17e5759, 0x17, 0x17ea587, 0x1c, 0x18a0398, 0x9, 0x18a0038, 0x8, 0x0, 0xc000315cf8, ...)
	github.com/CircleCI-Public/circleci-cli/update/update.go:46 +0x226
github.com/CircleCI-Public/circleci-cli/cmd.checkForUpdates(0xc0003021c0, 0x1, 0xc0002da6e8)
	github.com/CircleCI-Public/circleci-cli/cmd/check.go:37 +0x285
github.com/CircleCI-Public/circleci-cli/cmd.rootCmdPreRun(...)
	github.com/CircleCI-Public/circleci-cli/cmd/root.go:184
github.com/CircleCI-Public/circleci-cli/cmd.MakeCommands.func1(0xc000423400, 0x1cae728, 0x0, 0x0, 0x0, 0x0)
	github.com/CircleCI-Public/circleci-cli/cmd/root.go:97 +0x2d
github.com/spf13/cobra.(*Command).execute(0xc000423400, 0x1cae728, 0x0, 0x0, 0xc000423400, 0x1cae728)
	github.com/spf13/cobra@v0.0.5/command.go:805 +0x582
github.com/spf13/cobra.(*Command).ExecuteC(0xc0003fb180, 0x10014b0, 0x0, 0x0)
	github.com/spf13/cobra@v0.0.5/command.go:914 +0x30b
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v0.0.5/command.go:864
github.com/CircleCI-Public/circleci-cli/cmd.Execute()
	github.com/CircleCI-Public/circleci-cli/cmd/root.go:37 +0x2a
main.main()
	github.com/CircleCI-Public/circleci-cli/main.go:9 +0x25
```

**Comment by marcomorain** [comment]
Thanks for reporting this @alexjurkiewicz 

We've found that a third party changed the homebrew formula to add a new revision, which broke our parsing: https://github.com/Homebrew/homebrew-core/pull/81462/files

WIP to address this is in #611

**Comment by alexjurkiewicz** [comment]
Is there a workaround to disable the check?

**Comment by bjd2385** [comment]
Looks like this has been fixed in a recent release, could probably close?

**Comment by pete-woods** [comment]
The CLI has been rewritten from scratch for v1 (the `main` branch — `v0` is the legacy CLI that ships today and now takes critical fixes only).

**The v1 CLI has no update check at all.** It is distributed through Homebrew,
Chocolatey, winget, Snap, deb and GitHub releases, and lets those package managers own
updating. There is no `brew outdated` shell-out, no GitHub API poll, no
`update_check.yml`, and nothing printed before your command runs — so there is no
update check to be slow, to write to stdout, to panic on a version string, or to skip.

`--skip-update-check` still parses at the root (hidden) so existing v0 scripts and
orbs keep working; it is now a no-op.

Closing as resolved by the v1 rewrite.
