### ISSUE TITLE
Local Build/Execute fails with panic

### ISSUE THREAD

**Issue by sagarkar10** [CircleCI-Public/circleci-cli#665]
## Meta:

**CircleCI CLI Version:**
0.1.16535+5010eb7 (release)

**Operating System:**
MacOs: 12.1 (21C52)

**CircleCI CLI Diagnostic:**

```
---
CircleCI CLI Diagnostics
---
Debugger mode: false
Config found: /Users/$HOME/.circleci/cli.yml
API host: https://circleci.com
API endpoint: graphql-unstable
OK, got a token.
Trying an introspection query on API...
Ok.
Hello, <NAME>
```

---

## Current behavior:

```
$ pwd
~/circleci-demo-go #master: https://github.com/CircleCI-Public/circleci-demo-go
$ circleci build
Downloading latest CircleCI build agent...
Docker image digest: sha256:3b40ae3c6445ba88fefdcd6803e132c1a5a0999783d75640568ad20a766f1762
====>> Spin up environment
Build-agent version  ()
process panic
goroutine 1 [running]:
runtime/debug.Stack()
        /usr/local/go/src/runtime/debug/stack.go:24 +0x65
github.com/circleci/build-agent/cmd/internal/setup.PanicHandler()
        /mnt/ramdisk/circleci/project/cmd/internal/setup/handlers.go:23 +0x85
panic({0x1460aa0, 0x24a6dd0})
        /usr/local/go/src/runtime/panic.go:1038 +0x215
github.com/opencontainers/runc/libcontainer/cgroups/fs2.defaultDirPath(0xc0009e9a08)
        /home/circleci/go/pkg/mod/github.com/opencontainers/runc@v1.1.0/libcontainer/cgroups/fs2/defaultpath.go:35 +0x18
github.com/opencontainers/runc/libcontainer/cgroups/fs2.NewManager(0x0, {0x0, 0x0})
        /home/circleci/go/pkg/mod/github.com/opencontainers/runc@v1.1.0/libcontainer/cgroups/fs2/fs2.go:31 +0x2c
github.com/circleci/build-agent/outer/docker/cgroups.cgroupsV2({0xc0009d7a20, 0x8})
        /mnt/ramdisk/circleci/project/outer/docker/cgroups/cgroups_linux.go:51 +0x6e
github.com/circleci/build-agent/outer/docker/cgroups.GetSelf({0xc0009d7a20, 0x8})
        /mnt/ramdisk/circleci/project/outer/docker/cgroups/cgroups_linux.go:25 +0xa5
github.com/circleci/build-agent/outer/docker.NewDockerExecutorWithClient({{{{0xc000668270, 0x15}, {{...}, {...}, 0x0, 0x1, {...}, {...}, {...}, {...}, ...}, ...}, ...}, ...}, ...)
        /mnt/ramdisk/circleci/project/outer/docker/docker.go:70 +0x13e
github.com/circleci/build-agent/outer/docker.NewDockerExecutor({{{{0xc000668270, 0x15}, {{...}, {...}, 0x0, 0x1, {...}, {...}, {...}, {...}, ...}, ...}, ...}, ...}, ...)
        /mnt/ramdisk/circleci/project/outer/docker/docker.go:103 +0xdc
github.com/circleci/build-agent/outer.newExecutor({_, _}, {{{{0xc000668270, 0x15}, {{...}, {...}, 0x0, 0x1, {...}, {...}, ...}, ...}, ...}, ...}, ...)
        /mnt/ramdisk/circleci/project/outer/run.go:369 +0x265
github.com/circleci/build-agent/outer.ConfigureAndRun({_, _}, {{0xc00013c408, 0x15}, {0x0, 0x0}, {0xc00013c570, 0x16}, {0x0, 0x0}, ...})
        /mnt/ramdisk/circleci/project/outer/run.go:219 +0x17ad
github.com/circleci/build-agent/cmd/internal/outer/local.runExecuteJob(0xc00009e380, 0x0, {0x1988890, 0x0})
        /mnt/ramdisk/circleci/project/cmd/internal/outer/local/execute.go:125 +0x2b6
github.com/circleci/build-agent/cmd/internal/outer/local.NewExecuteJobCmd.func1(0xc00042d400, {0x165de4d, 0x2, 0x2})
        /mnt/ramdisk/circleci/project/cmd/internal/outer/local/execute.go:64 +0x29
github.com/spf13/cobra.(*Command).execute(0xc00042d400, {0xc0001326c0, 0x2, 0x2})
        /home/circleci/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:856 +0x60e
github.com/spf13/cobra.(*Command).ExecuteC(0xc00042d180)
        /home/circleci/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:974 +0x3bc
github.com/spf13/cobra.(*Command).Execute(...)
        /home/circleci/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:902
github.com/circleci/build-agent/cmd.Execute()
        /mnt/ramdisk/circleci/project/cmd/root.go:64 +0x2cf
main.main()
        /mnt/ramdisk/circleci/project/main.go:14 +0xca

```
## Expected behavior:

Runs with tests
## When did this begin / Was this previously working?:

New setup in local

## Additional Information:

Trying to run local tests

**Comment by Thorbenl** [comment]
Same problem here

**Comment by sagarkar10** [comment]
Can we get some help here! If anyone knows who to tag. Plesse do.

**Comment by Thorbenl** [comment]
Let this go up, seems like something that should be addressed.

**Comment by Thorbenl** [comment]
@sagarkar10 did u get anything to work?

**Comment by nblumoe** [comment]
@Thorbenl can you check if this is resolved for you on the latest build agent? For me it was: https://github.com/CircleCI-Public/circleci-cli/issues/589#issuecomment-1027024167

**Comment by am-bui** [comment]
Previously, `circleci local execute` cached the latest build-agent version indefinitely unless it is manually updated via `circleci update build-agent`.

**The caching functionality has been removed. With this change, users will be automatically prompted to update the CLI.**

Eliminating the caching altogether:
We do not want to store the cache anymore to avoid staleness.
Now, every time a user runs local execute, the code will run with the latest image each time.

Implications:
`circleci local execute` may be slow without the cache.

Let us know if you're still having trouble!
