### ISSUE TITLE
CLI crashes on M1 Mac

### ISSUE THREAD

**Issue by gavinclarkeuk** [CircleCI-Public/circleci-cli#838]
Installed the latest circleci cli (0.1.23391) to an M1 mac via homebrew. It just crashes with the below stack trace no matter what command I run.

I've also tried installing using the curl & install.sh, but the install just fails.

```
panic: stat /Users/gavin.clarke/.circleci/cli.yml: not a directory

goroutine 1 [running]:
github.com/CircleCI-Public/circleci-cli/cmd.MakeCommands()
        github.com/CircleCI-Public/circleci-cli/cmd/root.go:109 +0xda8
github.com/CircleCI-Public/circleci-cli/cmd.CommandStr()
        github.com/CircleCI-Public/circleci-cli/cmd/root.go:54 +0x1c
github.com/CircleCI-Public/circleci-cli/cmd.Execute()
        github.com/CircleCI-Public/circleci-cli/cmd/root.go:43 +0x1c
main.main()
        github.com/CircleCI-Public/circleci-cli/main.go:9 +0x1c
panic: stat /Users/gavin.clarke/.circleci/cli.yml: not a directory

goroutine 1 [running]:
github.com/CircleCI-Public/circleci-cli/cmd.MakeCommands()
        github.com/CircleCI-Public/circleci-cli/cmd/root.go:109 +0xda8
github.com/CircleCI-Public/circleci-cli/cmd.CommandStr()
        github.com/CircleCI-Public/circleci-cli/cmd/root.go:54 +0x1c
github.com/CircleCI-Public/circleci-cli/cmd.Execute()
        github.com/CircleCI-Public/circleci-cli/cmd/root.go:43 +0x1c
main.main()
        github.com/CircleCI-Public/circleci-cli/main.go:9 +0x1c
```

## Meta:

**CircleCI CLI Version:**

0.1.23391

**Operating System:**

MacOS Monteray 12.5.1

**CircleCI CLI Diagnostic:**

Crashes

---

## Current behavior:

Running `circleci` just crashes

## Expected behavior:
CLI should work

## When did this begin / Was this previously working?:
Since installation

**Comment by gavinclarkeuk** [comment]
Actually I just realised that this is being caused because I had a `~/.circleci` file that is preventing creating of a config directory. Renaming that file fixed the issue
